[merge] feat/2/kyoungmin
SPOTeam/Server pull request #12
Opened 2024-07-15 17:27 UTC by FromKyoung

## #️⃣ 연관된 이슈

> https://github.com/SPOTeam/Server/issues/2

<br/>

## 🔎 작업 내용

> 엔티티 매핑

<br/>

## 📷 스크린샷 (선택)
> 작업한 결과물에 대한 간단한 스크린샷을 올려주세요.
> 
<br/>

## 💬리뷰 요구사항 (선택)

> 코드 확인 부탁드립니다~

2024-07-16 02:09 UTC, msk226 approved these changes
코드는 문제 없는 것 같네요!

 PR 작성 하실 때 Reviewers나 Assignees도 꼭 설정 해주시면 좋을 것 같아요~ Reviewers에는 저희 서버 팀원들, Assignees에는 코드 작성한 본인을 설정 하시면 됩니다. 
 
 PR naming도 앞으로 이슈 이름이랑 똑같은걸로 하는걸로 할까요? 이 부분에 대해서는 금일 회의 때 조금 더 이야기 나눠봅시다! 
 
 고생하셨습니다!

2024-07-16 06:56 UTC, FromKyoung commented
넵 감사합니다~앞으로 적용하겠습니다!!

2024-07-16 07:02 UTC, dvlp-sy approved these changes

2024-07-16 07:02 UTC, dvlp-sy commented on src/main/java/com/example/spot/domain/PostComment.java
> +    @Setter
코드 잘 읽어보았습니다! 문제 없이 잘 작성해주신 것 같아요 ㅎㅎ

그런데 혹시 여기에 Setter를 추가한 이유가 있으신가요??
Setter는 추후에 API 개발하면서 정말 필요한 상황에만 추가하는 게 좋을 것 같아서요..!

2024-07-16 08:29 UTC, FromKyoung commented on src/main/java/com/example/spot/domain/PostComment.java
> +    @Setter
네넵 감사합니당 수정하겠습니다!!

2024-07-17 03:48 UTC, msk226 commented on src/main/java/com/example/domain/LikedPostComment.java
> +    private PostComment postComment;
이 파일에 `PostComment` 의존성 추가가 안되어있네요

2024-07-17 03:49 UTC, msk226 commented on src/main/java/com/example/spot/domain/PostComment.java
> +    private List<LikedPostComment> likedPostCommentsList = new ArrayList<>();
이 파일도 `LikedPostComment` 의존성 추가가 안되어있어서 에러 발생하는 것 같습니다!

2024-07-17 04:00 UTC, msk226 requested changes
`PreferredRegion`클래스에 21번째 라인부터 주석 처리 되어있는데, 그 부분 해제 안하시면 아마 실행 안될거에요. 그 부분도 주석 해제 부탁드립니다.

2024-07-17 04:10 UTC, msk226 approved these changes
수고하셨습니다!

2024-07-17 04:13 UTC, merged