[feat] 스터디 일정 관련 API 구현
SPOTeam/Server pull request #58
Opened 2024-07-27 06:42 UTC by dvlp-sy

## #️⃣ 연관된 이슈

> ex) #이슈 번호, #이슈 링크 

- #48 

<br/>

## 🔎 작업 내용

> 기능에서 어떤 부분이 구현되었는지 설명해주세요.

- [스터디 일정] 월별 일정 불러오기
- [스터디 일정] 상세 일정 불러오기
- [스터디 일정] 일정 추가하기
- [스터디 일정] 일정 변경하기

<br/>

## 📷 스크린샷 (선택)
> 작업한 결과물에 대한 간단한 스크린샷을 올려주세요.
> 
<br/>

## 💬리뷰 요구사항 (선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.

2024-07-27 06:47 UTC, FromKyoung approved these changes
확인했습니다!

2024-07-28 07:47 UTC, msk226 requested changes
충돌 빠른 해결 부탁드립니다!

2024-07-28 07:51 UTC, dvlp-sy commented
> 충돌 빠른 해결 부탁드립니다! 

죄송합니다. 아르바이트 끝나는대로 바로 수정 작업 진행할게요!

2024-07-28 12:49 UTC, msk226 approved these changes
테스트 해보니 문제 없는 것 같아요! 수고 많으셨습니다!

2024-07-28 12:51 UTC, merged